name: app_template
description: Template 
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobx: ^2.2.0
  flutter_mobx:
  get: ^4.6.5
  dio: ^5.1.1
  retrofit: ^4.0.1
  flutter_dotenv: ^5.0.2
  envied: ^0.3.0+3
  envify: ^2.0.3
  

dev_dependencies:
  build_runner:
  mobx_codegen: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable:
  retrofit_generator:
  envied_generator: ^0.3.0+3



flutter:
  uses-material-design: true

